import React, { useState, useEffect } from 'react';
import { BookOpen, Target, Clock, AlertTriangle, Plus, Trash2 } from 'lucide-react';
import api from '../api/client';

export default function Tasks() {
  const [activeTab, setActiveTab] = useState<'assignments' | 'exams' | 'subjects'>('assignments');
  const [subjects, setSubjects] = useState<any[]>([]);
  
  // Assignment Form State
  const [assignTitle, setAssignTitle] = useState('');
  const [assignSubject, setAssignSubject] = useState('');
  const [assignDeadline, setAssignDeadline] = useState('');
  const [assignDuration, setAssignDuration] = useState('');
  const [assignDiff, setAssignDiff] = useState('');

  // Exam Form State
  const [examSubject, setExamSubject] = useState('');
  const [examDate, setExamDate] = useState('');
  const [examTopics, setExamTopics] = useState([{ title: '', duration: '', difficulty: '' }]);

  const [newSubjectName, setNewSubjectName] = useState('');

  const fetchSubjects = async () => {
    const res = await api.get('/subjects');
    setSubjects(res.data);
  };
  useEffect(() => { fetchSubjects(); }, []);

  const handleAddSubject = async () => {
    if (!newSubjectName) return;
    await api.post('/subjects', { name: newSubjectName, color: '#3B82F6' });
    setNewSubjectName('');
    fetchSubjects();
  };

  const handleCreateAssignment = async () => {
    if (!assignTitle || !assignSubject || !assignDeadline) return;
    const durInMins = assignDuration ? Math.round(parseFloat(assignDuration) * 60).toString() : '';
    await api.post('/tasks/assignment', {
      title: assignTitle, subjectId: assignSubject, deadline: assignDeadline, duration: durInMins, difficulty: assignDiff
    });
    alert('Assignment created!');
    setAssignTitle(''); setAssignDeadline(''); setAssignDuration(''); setAssignDiff('');
  };

  const handleCreateExam = async () => {
    if (!examSubject || !examDate) return;
    const formattedTopics = examTopics.filter(t => t.title).map(t => ({
       ...t, 
       duration: t.duration ? Math.round(parseFloat(t.duration) * 60).toString() : ''
    }));
    await api.post('/tasks/exam', {
      subjectId: examSubject, examDate, topics: formattedTopics
    });
    alert('Exam tracked! Revision slots will be generated by the scheduler.');
    setExamDate(''); setExamTopics([{ title: '', duration: '', difficulty: '' }]);
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
       <div className="flex justify-between items-center">
         <h1 className="text-3xl font-bold">Tasks & Study Planning</h1>
       </div>

       <div className="flex space-x-2 border-b border-gray-800 pb-2">
         {['assignments', 'exams', 'subjects'].map(tab => (
           <button key={tab} onClick={() => setActiveTab(tab as any)} className={`px-4 py-2 font-medium rounded-lg capitalize transition-colors ${activeTab === tab ? 'bg-blue-600 text-white shadow-lg shadow-blue-500/20' : 'text-gray-400 hover:text-white hover:bg-gray-800'}`}>
             {tab}
           </button>
         ))}
       </div>

       {activeTab === 'subjects' && (
         <div className="bg-gray-900 border border-gray-800 p-6 rounded-xl space-y-4 max-w-2xl">
            <h2 className="text-xl font-bold flex items-center gap-2"><BookOpen className="w-5 h-5"/> Manage Subjects</h2>
            <div className="flex gap-4">
               <input placeholder="New Subject Name" value={newSubjectName} onChange={e => setNewSubjectName(e.target.value)} className="flex-1 bg-gray-800 border border-gray-700 rounded-lg px-4 py-3 focus:outline-none focus:border-blue-500" />
               <button onClick={handleAddSubject} className="bg-blue-600 px-8 rounded-lg font-medium hover:bg-blue-500 transition-colors">Add Subject</button>
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-4 mt-6">
               {subjects.map(s => <div key={s.id} className="p-4 bg-gray-800 border border-gray-700 rounded-lg font-medium text-center shadow-sm">{s.name}</div>)}
            </div>
         </div>
       )}

       {activeTab === 'assignments' && (
         <div className="bg-gray-900 border border-gray-800 p-8 rounded-xl space-y-6 max-w-2xl shadow-xl">
            <h2 className="text-2xl font-bold text-white flex items-center gap-2 mb-2"><Target className="w-6 h-6 text-blue-500"/> New Assignment</h2>
            <p className="text-gray-400 text-sm bg-blue-900/20 text-blue-200 p-3 rounded-lg border border-blue-900/50"><strong>AI Assist Enabled:</strong> If duration and difficulty are left blank, the Artificial Intelligence engine will automatically predict them.</p>
            
            <div>
              <label className="block text-sm font-medium text-gray-400 mb-1">Title</label>
              <input placeholder="e.g. Chapter 4 Math Quiz" className="w-full bg-gray-800 border border-gray-700 rounded-lg p-3 text-white focus:outline-none focus:border-blue-500" value={assignTitle} onChange={e => setAssignTitle(e.target.value)} />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-400 mb-1">Subject</label>
                <select className="w-full bg-gray-800 border border-gray-700 rounded-lg p-3 text-white focus:outline-none focus:border-blue-500" value={assignSubject} onChange={e => setAssignSubject(e.target.value)}>
                  <option value="">Select Subject</option>
                  {subjects.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
                </select>
              </div>
              <div>
                 <label className="block text-sm font-medium text-gray-400 mb-1">Deadline Date</label>
                 <input type="date" className="w-full bg-gray-800 border border-gray-700 rounded-lg p-3 text-white focus:outline-none focus:border-blue-500" value={assignDeadline} onChange={e => setAssignDeadline(e.target.value)} />
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
               <div>
                  <label className="block text-sm font-medium text-gray-400 mb-1">Manual Duration (Hours)</label>
                  <input type="number" step="0.5" placeholder="e.g. 1.5" className="w-full bg-gray-800 border border-gray-700 rounded-lg p-3 text-white focus:outline-none focus:border-blue-500" value={assignDuration} onChange={e => setAssignDuration(e.target.value)} />
               </div>
               <div>
                 <label className="block text-sm font-medium text-gray-400 mb-1">Manual Difficulty</label>
                 <select className="w-full bg-gray-800 border border-gray-700 rounded-lg p-3 text-white focus:outline-none focus:border-blue-500" value={assignDiff} onChange={e => setAssignDiff(e.target.value)}>
                   <option value="">AI Auto-Detect</option>
                   <option value="Easy">Easy</option><option value="Medium">Medium</option><option value="Hard">Hard</option>
                 </select>
               </div>
            </div>

            <button onClick={handleCreateAssignment} className="w-full bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 py-3 rounded-lg font-medium text-white shadow-lg transition-all mt-4">Save Assignment</button>
         </div>
       )}

       {activeTab === 'exams' && (
         <div className="bg-gray-900 border border-gray-800 p-8 rounded-xl space-y-6 max-w-3xl shadow-xl">
           <div className="flex items-center gap-2 mb-2"><AlertTriangle className="w-6 h-6 text-yellow-500"/><h2 className="text-2xl font-bold">Upcoming Exam Tracker</h2></div>
           <p className="text-gray-400 text-sm bg-yellow-900/20 text-yellow-200 border border-yellow-900/50 p-3 rounded-lg">Input the specific topics covered in your exam. The heuristic scheduling engine will intelligently distribute spaced-repetition slots prior to the deadline date.</p>

           <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-400 mb-1">Exam Subject</label>
                <select className="w-full bg-gray-800 border border-gray-700 rounded-lg p-3 text-white focus:outline-none focus:border-yellow-500" value={examSubject} onChange={e => setExamSubject(e.target.value)}>
                  <option value="">Select Subject</option>
                  {subjects.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
                </select>
              </div>
              <div>
                 <label className="block text-sm font-medium text-gray-400 mb-1">Exam Date</label>
                 <input type="date" className="w-full bg-gray-800 border border-gray-700 rounded-lg p-3 text-white focus:outline-none focus:border-yellow-500" value={examDate} onChange={e => setExamDate(e.target.value)} />
              </div>
            </div>

            <div className="space-y-4 pt-4">
              <h3 className="font-semibold text-gray-300 border-b border-gray-800 pb-2">Exam Syllabus / Topic List</h3>
              {examTopics.map((topic, i) => (
                 <div key={i} className="flex gap-4 items-end bg-gray-800/50 p-3 rounded-lg border border-gray-800">
                    <div className="flex-1"><label className="text-xs font-medium text-gray-400 mb-1 block">Topic Name</label><input type="text" placeholder="e.g. Kinematics" value={topic.title} onChange={e => { const newT = [...examTopics]; newT[i].title = e.target.value; setExamTopics(newT); }} className="w-full bg-gray-950 border border-gray-700 rounded-lg p-2.5 text-sm text-white focus:outline-none focus:border-yellow-500" /></div>
                    <div className="w-24"><label className="text-xs font-medium text-gray-400 mb-1 block">Hours</label><input type="number" step="0.5" placeholder="AI" value={topic.duration} onChange={e => { const newT = [...examTopics]; newT[i].duration = e.target.value; setExamTopics(newT); }} className="w-full bg-gray-950 border border-gray-700 rounded-lg p-2.5 text-sm text-white focus:outline-none focus:border-yellow-500" /></div>
                    <div className="w-32"><label className="text-xs font-medium text-gray-400 mb-1 block">Diff</label><select value={topic.difficulty} onChange={e => { const newT = [...examTopics]; newT[i].difficulty = e.target.value; setExamTopics(newT); }} className="w-full bg-gray-950 border border-gray-700 rounded-lg p-2.5 text-sm text-white focus:outline-none focus:border-yellow-500"><option value="">Auto</option><option value="Easy">Easy</option><option value="Medium">Medium</option><option value="Hard">Hard</option></select></div>
                 </div>
              ))}
              <div className="mt-2">
                 <button onClick={() => setExamTopics([...examTopics, { title: '', duration: '', difficulty: '' }])} className="text-sm text-yellow-500 flex items-center gap-1 hover:text-yellow-400 bg-yellow-900/30 px-3 py-1.5 rounded-lg transition-colors"><Plus className="w-4 h-4"/> Add Topic</button>
              </div>
            </div>

            <button onClick={handleCreateExam} className="w-full bg-gradient-to-r from-yellow-600 to-amber-600 hover:from-yellow-500 hover:to-amber-500 py-3 rounded-lg font-medium text-white shadow-lg transition-all mt-6">Track Exam & Generate Syllabus Plan</button>
         </div>
       )}
    </div>
  );
}
